oacore/reader

.babelrc
.browserslistrc
.gitignore
package.json
webpack/constants.js
webpack/webpack.config.babel.js
webpack/webpack.config.devel.babel.js
yarn.lock

@viktor-yakubiv Not sure if you want to do a review. If not feel free to merge. This PR is just about some basic setup of webpack and installing some necessary npm packages.

Basic setup

---

.babelrc
package.json
src/CoreReader.jsx
src/CoreReader.scss
src/components/header/Header.scss
src/components/pdf-loader/PDFLoader.jsx
src/components/pdf-loader/PDFLoader.scss
src/components/pdf-viewer/PDFViewer.jsx
src/components/pdf-viewer/PDFViewer.scss
src/store/GlobalProvider.jsx
src/store/configureContext.js
src/store/withAppContext.jsx
webpack/webpack.config.babel.js
yarn.lock

@viktor-yakubiv This PR adds support for rendering PDF. I created a simple CSS flex layout with NavBar and rendered PDF bellow it. The buttons are not clickable yet and need polishing but it should be :ok_hand: for now. Also, I created one global store for storing app state.

Simple PDF rendering

---

.eslintrc.yml
package.json
src/CoreReader.jsx
src/CoreReader.scss
src/components/header/Header.jsx
src/components/icons/Icon.jsx
src/components/icons/Icon.scss
src/components/main-area/MainArea.jsx
src/components/main-area/MainArea.scss
src/components/pdf-loader/PDFLoader.jsx
src/components/pdf-thumbnails-sidebar/PDFThumbnailSidebar.jsx
src/components/pdf-thumbnails-sidebar/PDFThumbnailSidebar.scss
src/components/pdf-viewer/PDFViewer.jsx
src/components/pdf-viewer/PDFViewer.scss
src/lib/pdf-js/PDFThumbnailView.js
src/lib/pdf-js/PDFThumbnailViewer.js
src/store/GlobalProvider.jsx
yarn.lock

@viktor-yakubiv Unfortunately this PR is kind of a mess it's just one big commit. I didn't split it into more commits and didn't want to spend much time on it since it gets squashed anyway. I don't expect you to do a review.

Add PDF thumbnails sidebar

---

src/components/pdf-outline-sidebar/PDFOutlineSidebar.jsx
src/components/pdf-outline-sidebar/PDFOutlineSidebar.scss
src/components/pdf-outline-sidebar/renderers/OutlineRenderer.jsx

Closes https://github.com/oacore/reader/issues/14

Sidebar with TOC accessibility

---

.babelrc
package.json
src/components/main-area/MainArea.jsx
src/components/pdf-enhancement-sidebar/PDFEnhancementSidebar.jsx
src/components/pdf-enhancement-sidebar/PDFEnhancementSidebar.scss
src/components/pdf-highlighter/PDFHighlighter.jsx
src/components/pdf-highlighter/PDFHighlighter.scss
src/components/pdf-highlighter/components/ContextMenu.jsx
src/components/pdf-highlighter/components/Highlight.jsx
src/components/pdf-highlighter/components/Highlights.jsx
src/components/pdf-highlighter/utils/layer.js
src/components/pdf-highlighter/utils/rects.js
src/components/pdf-highlighter/utils/utils.js
src/components/pdf-toolbar/PDFToolbar.scss
src/components/pdf-viewer/PDFViewer.scss
src/store/GlobalProvider.jsx
src/utils/debounce.js
src/utils/throttle.js
yarn.lock

Part of https://github.com/oacore/reader/issues/33

Highlights

---

src/CoreReader.jsx
src/components/layout/index.jsx
src/components/layout/layout.scss
src/components/main-area/MainArea.scss
src/components/pdf-loader/PDFLoader.scss
src/index.template.html

Fixes `7vh`/`93vh` issue and viewports in general.
Solved by adding CSS to top-level containers, `body` and `html`. It required development of the `Layout` component.
---
Also fixes sidebar shadow with `z-index`.

Fix application height

---

.github/workflows/pull-request-check.yml

@viktor-yakubiv Github actions are up and running. We should replace TravisCI with them as they are integrated with GitHub. 🙂

Create Action for Pull Request Check

---

reader/components/outline-sidebar/OutlineSidebar.jsx
reader/components/outline-sidebar/OutlineSidebar.scss
reader/components/recommender/Recommender.scss

@viktor-yakubiv You may use this ID 196558092

Show missing outline message

---

next.config.js
package-lock.json
package.json

Include 3rd party source maps for better Sentry error tracking

Add source map loader

---

reader/components/pdf-loader/PDFLoader.jsx

@samuelpearce I went for 5 seconds as 10 seconds seemed to be much.

Postpone redirection for TDM papers

---

package-lock.json
package.json

Revert "Bump core-js from 3.4.1 to 3.6.4"

---

reader/components/outline-sidebar/OutlineSidebar.jsx
reader/components/recommender/Recommender.jsx
reader/components/toolbar/Toolbar.jsx
reader/store/ui/actions.js
reader/store/ui/reducers.js

https://sentry.io/organizations/oacore/issues/1448432591/?project=1806836&query=is%3Aunresolved
More info commits

Fix localstorage in Safari incognito

---

reader/components/recommender/Recommender.jsx

https://sentry.io/organizations/oacore/issues/1519848201/?project=2091955&query=is%3Aunresolved

Fix localStorage not accessible when cookies disabled

---

package-lock.json
package.json
polyfills.js

https://sentry.io/organizations/oacore/issues/1550852570/?project=1806836&query=is%3Aunresolved

Add performance polyfill

---

package-lock.json
package.json

Revert "Bump next-images from 1.2.0 to 1.4.0"

---

pages/_app.jsx
reader/components/loading-bar/index.jsx
reader/components/loading-bar/styles.module.css
reader/components/main-area/MainArea.jsx
reader/components/pdf-loader/PDFLoader.scss
reader/components/pdf-loader/document-placeholder.jsx
reader/components/pdf-loader/pdf-loader.jsx
reader/components/pdf-loader/styles.module.scss
reader/index.jsx

@viktor-yakubiv What do you think about this Facebook like loading animation instead of spinner? Also, I was thinking about moving `LoadingBar` to design as we use it here and in dashboard.

Add document placeholder

---

.stylelintrc.yml
package-lock.json
package.json
pages/styles.css
postcss.config.js
reader/components/enhancement-sidebar/styles.module.css
reader/components/header/styles.module.css
reader/components/main-area/styles.module.css
reader/components/outline-sidebar/outline-renderer.jsx
reader/components/outline-sidebar/styles.module.css
reader/components/pdf-loader/styles.module.css
reader/components/recommender/index.jsx
reader/components/thumbnails-sidebar/styles.module.css
reader/components/toolbar/styles.module.css
reader/lib/pdf-js/PDFThumbnailView.js

I am thinking moving stylelint c& postcss config to @oacore/configs. Anything against?

Use custom postcss config

---

pages/[pdfId].jsx

@viktor-yakubiv Maybe we could use this for `/user` in Dashboard too. :)

Preload PDF

---

reader/components/recommender/index.jsx
reader/components/recommender/styles.module.css

Allow to click on recommendations

---

next.config.js

Caused hard refresh on every change

Fix applying polyfills

---

pages/[pdfId].jsx

Fixed downloadLink variable because of a change in the Core API

Fixed downloadLink variable
